#page title
page_title                                : GoHyper                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
#ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : au                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
                                                                                    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : ./assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : GoHyper                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Decentralized Ridesharing, Empowered by Bitcoin and Driven by You

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : The HyperLabs                                
your_link                                 : https://thehyperlabs.com                     
your_city                                 : Poland 🇵🇱                               
email_address                             : hello@thehyperlabs.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 
funder_name                               : Don't Trust Verify Foundation 
funder_link                               : https://donttrustverify.org
funder_city                               : Australia 🇦🇺                               


# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title: Built on <a href="https://gig-gossip.org/">Gig-Gossip</a>
    description: GoHyper is built on the <a href="https://gig-gossip.org/">Gig-Gossip</a> protocol, a decentralized P2P gig economy platform on top of <a href="https://bitcoin.org">Bitcoin</a> and <a href="https://nostr.com/">NOSTR</a>. <a href="https://gig-gossip.org/">Gig-Gossip</a> revolutionizes the way services are offered and accessed, enabling direct connections, secure payments, and decentralized operations.
    fontawesome_icon_name: fas fa-cogs
    
  - title: Pay by <a href="https://bitcoin.org">Bitcoin</a> with <a href="https://lightning.network/">Lightning Network</a>
    description: GoHyper rewards its users with bitcoins, even just for routing messages! Embrace the future with secure, transparent, and efficient payment processing using <a href="https://bitcoin.org">Bitcoin</a> .
    fontawesome_icon_name: fab fa-bitcoin

  - title: Build on top of <a href="https://nostr.com/">NOSTR</a>
    description: GoHyper uses the <a href="https://nostr.com/">NOSTR</a> protocol for decentralized communication capabilities, ensuring secure and streamlined interactions within its ridesharing network.
    fontawesome_icon_name: fas fa-network-wired

  - title: Decentralized Operation
    description: GoHyper's decentralized framework guarantees a more equitable and open marketplace, fostering trust and empowerment among its users.
    fontawesome_icon_name: fas fa-globe

  - title: Peer-to-Peer Connectivity
    description: Experience a personalized travel journey with GoHyper's peer-to-peer connection feature, which lets riders directly connect with drivers, bypassing centralized systems for a more tailored and human-centric ridesharing experience.
    fontawesome_icon_name: fas fa-users

  - title: User-Driven Pricing
    description: Engage in direct price negotiations, fostering a competitive and fair pricing environment that adapts to real-time market demands.
    fontawesome_icon_name: fas fa-hand-holding-usd

  - title: Instant Booking
    description: Experience the convenience of instant booking, with real-time availability and quick response times ensuring your plans stay on track.
    fontawesome_icon_name: fas fa-bolt

  - title: 24/7 Support
    description: Security is a top priority at GoHyper. Security Centers perform thorough KYC and driver screening, ensuring only trusted individuals are behind the wheel. They also handle final payment settlements post-dispute resolutions, maintaining the integrity and trust of the GoHyper ecosystem.
    fontawesome_icon_name: fas fa-shield-alt

  - title: Community Ratings
    description: Security Centers also oversee the Community Ratings, ensuring fairness and accuracy. This system upholds the highest standards of service and reliability, reflecting genuine user experiences and driver performance.
    fontawesome_icon_name: fas fa-thumbs-up


# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0.9
topbar_title_color                        : "#000000"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#FFFFFF"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#80c37f"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#80c37f"
feature_icons_background_color            : "#FFFFFF"

social_icons_foreground_color             : "#FFFFFF"
social_icons_background_color             : "#80c37f"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
